name: check_update
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  update:
    name: checkversion
    runs-on: windows-latest
    steps:
      - name: Checkout Bucket
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: motty-mio2/scoop-bucket
          path: "bucket"
      - name: Checkout Scoop
        uses: actions/checkout@v3
        with:
          repository: ScoopInstaller/Scoop
          path: "scoop_core"
      - name: check_version
        shell: pwsh
        run: |
          git config --global user.email "motty.mio2@gmail.com"
          git config --global user.name "Github Actions"
          . "$(Convert-Path '.\bucket\check_scoop.ps1')" -repo "$(Convert-Path '.\bucket')" -SCOOP_HOME "$(Convert-Path '.\scoop_core')"
        env:
          GH_TOKEN: ${{ github.token }}
